### ISSUE TITLE
Annotation path in Relation corpus is wrong

### ISSUE THREAD

**Issue by kkjh0723** [om-ai-lab/VL-CheckList#11]
https://github.com/om-ai-lab/VL-CheckList/blob/9e6b5ef13e1133bfa37d54748d368e46d80dfdb1/corpus/v1/Relation/spatial/vg.yaml#L1

I think `Attribute` should be fixed to `Relation`.

**Comment by kyusonglee** [comment]
Thanks! Fixed!
