### ISSUE TITLE
Running test with other models

### ISSUE THREAD

**Issue by alfassy** [om-ai-lab/VL-CheckList#7]
Hi! 
Thank you for publishing this great work. I was able to run test with your Vilt model, is it possible to run test with other models such TCL and the rest? their checkpoints are different so it's not clear to me if the code should support it or not.
Thank you and have a great week,
Amit

**Comment by kyusonglee** [comment]
I'm glad to hear you were able to test the ViLT model successfully. Regarding testing other models, such as TCL, you can use the "albef example" provided in the code. This should allow you to run TCL.
